### PR TITLE
Linear Algebra - Matrices - Basic Operations

### PR DESCRIPTION
**Pull request by khodeprasad**

### CODE REVIEW

**Comment by pktippa** [comment]
@khodeprasad thanks for raising the pull request, please add a link in the README.md file pointing to this.

Also move this file to "python_notebooks" folder.

**Review by pktippa — CHANGES_REQUESTED** [review]
Please move this file to "python_notebooks" folder.

**Comment by khodeprasad** [comment]
@pktippa review changes are done...

**Review by pktippa — APPROVED** [review]

**Comment by pktippa** [comment]
Approving now, with doing the changes by my own.

**Pull request merged**
